#!/usr/bin/with-contenv bash
set -eux

HOST=$(getent hosts ${RPC_HOST} | awk '{ print $1 }')
# copy config
# [[ ! -s /etc/lighttpd/lighttpd.conf ]] && \
mv /etc/lighttpd/lighttpd.conf /etc/lighttpd/lighttpd.conf.default
cp /defaults/lighttpd.conf /etc/lighttpd/lighttpd.conf
# sed -i -e "s~host:\(.*\) 'localhost',~host:\1 '${HOST:-localhost}',~g" /app/www/configuration.js
sed -i -e "s~host:\(.*\) 'localhost',~host: '${HOST:-localhost}',~g" /app/www/configuration.js
sed -i -e "s~port: \d\+,~port: ${RPC_PORT:-6800},~g" /app/www/configuration.js
sed -i -e "s~// token:.*~  token: '${RPC_SECRET:-}'~g" /app/www/configuration.js

chown -R lighttpd:lighttpd \
    /app

chown -R abc:abc \
    /config
